[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std=lib/forge-std/src", "@openzeppelin=lib/openzeppelin-contracts"]
evm_version = "shanghai"

[fmt]
sort_imports = true
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
quote_style = "double"
tab_width = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
